/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.autonoma.gui;

import co.edu.autonoma.elements.Canvas;
import co.edu.autonoma.elements.Drawable;
import co.edu.autonoma.elements.TurtleCommandReader;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author HP-15EC107LA
 */
public class MainWindow extends javax.swing.JFrame implements Drawable{
    private Canvas canvas;
    private TurtleCommandReader reader;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        setResizable(false);
        initComponents();
        
    }
    
    public void setCanvas(Canvas canvas){
        this.canvas = canvas;
        canvas.setDrawable(this);
        reader= new TurtleCommandReader(canvas);
    }
    

    @Override
    public void paint(Graphics g){
        super.paint(g);
        canvas.draw(g);
        g.setColor(Color.black);
        g.drawLine(0, 390, getWidth(), 390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccept = new javax.swing.JButton();
        txtCommandText = new javax.swing.JTextField();
        btnShowList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        txtCommandText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommandTextActionPerformed(evt);
            }
        });

        btnShowList.setText("Show list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtCommandText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnAccept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnShowList)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccept)
                    .addComponent(btnShowList))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommandTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommandTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommandTextActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        String data = this.txtCommandText.getText().toLowerCase();
        String[] array= data.split(" ");
        reader.read(array);
        repaint();
    }//GEN-LAST:event_btnAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainWindow window = new MainWindow();
        Canvas canvas = new Canvas(window.getWidth(), window.getHeight());
        
        
        window.setCanvas(canvas);
//        garden.setWidth(window.getWidth());
//        garden.setHeight(window.getHeight());
        
        window.setTitle("Logo UAM");
        window.setVisible(true);
    }

    @Override
    public void redraw() {
        repaint();
    }

    @Override
    public void redraw(int x, int y, int width, int height) {
        repaint(x, y, width, height);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnShowList;
    private javax.swing.JTextField txtCommandText;
    // End of variables declaration//GEN-END:variables
}
