/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.autonoma.gui;

import co.edu.autonoma.elements.Canvas;
import co.edu.autonoma.elements.Drawable;
import java.awt.Graphics;

/**
 *
 * @author HP-15EC107LA
 */
public class MainWindow extends javax.swing.JFrame implements Drawable{
    private Canvas canvas;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }
    
    public void setCanvas(Canvas canvas){
        this.canvas = canvas;
        canvas.setDrawable(this);
    }
    
    @Override
    public void paint(Graphics g){
        canvas.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainWindow window = new MainWindow();
        Canvas canvas = new Canvas(window.getWidth(), window.getHeight());
        
        window.setCanvas(canvas);
//        garden.setWidth(window.getWidth());
//        garden.setHeight(window.getHeight());
        
        window.setTitle("Logo UAM");
        window.setVisible(true);
    }

    @Override
    public void redraw() {
    }

    @Override
    public void redraw(int x, int y, int width, int height) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
